# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
   push:
      branches: ["main"]
      paths-ignore:
         - "**/*.md"
         - "**/*.gitignore"
         - "**/*.gitattributes"
   pull_request:
      branches: ["main"]

env:
   DOTNET_NOLOGO: true
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
   DOTNET_CLI_TELEMETRY_OPTOUT: true
   dotnet_version: net9.0-android
   signing_key_alias: einburgerung

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: Setup .NET
           uses: actions/setup-dotnet@v4
           with:
              dotnet-version: 9.0.x

         - name: Install Maui andriod workload
           run: dotnet workload install maui-android

         - name: List installed MAUI workload(s)
           run: dotnet workload list

         - name: Restore dependencies
           run: dotnet restore
           working-directory: .

         - name: Build application
           run: dotnet build -c Release -f $dotnet_version --no-restore

         - name: Test
           run: dotnet test --no-build --verbosity normal
