# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Install Maui andriod workload
      run: dotnet workload install maui-android
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: .
      
    - name: Build application
      run: dotnet build --no-restore
      working-directory: .
      
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
